# Generated by Django 3.2.3 on 2021-06-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100)),
                ('pro_brand', models.CharField(max_length=100)),
                ('pro_img', models.ImageField(upload_to='Images')),
            ],
        ),
    ]
