# Generated by Django 3.2.3 on 2021-07-03 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='pro_category',
            field=models.CharField(choices=[('Mob', 'Mobile'), ('Lap', 'Laptop'), ('Cam', 'Camera'), ('Ear', 'Earphone')], default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pro_desc',
            field=models.TextField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='pro_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_brand',
            field=models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Mi', 'Mi'), ('Realme', 'Realme')], max_length=10),
        ),
    ]
