# Generated by Django 3.2.3 on 2021-08-06 14:40

import autoslug.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210703_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='pro_name', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
