# Generated by Django 3.2.3 on 2021-08-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210806_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pro_slug',
        ),
    ]
